name: Digital Media

baseurl: "/digital-media"
theme_assets: "/digital-media/theme/assets"
theme_images: "/digital-media/theme/assets/images"
course_images: "/digital-media/media/images"

markdown: kramdown
highlighter: null # disable syntax highlighting locally

kramdown:
  input: GFM
  enable_coderay: false
  hard_wrap: true
  # disable syntax highlighting on github pages
  syntax_highlighter_opts:
    disable : true

# Where things are
source:       .
destination:  ./_site
layouts_dir:  ./theme/_layouts
includes_dir: ./theme/_includes
sass:
    sass_dir: ./theme/_sass

# custom collections
collections:
  courses:
    output: true

# default settings
defaults:
  -
    scope:
      path: ""
      type: "courses"
    values:
      layout: "chapter"

# theme
themecolor: "#9b3a00"

# keep the built site tidy, only include files we need for publishing
exclude: ["node_modules", "Gemfile", "Gruntfile.js", "package.json", "README.md", "*.sublime-project", "*.sublime-workspace"]
